### ISSUE TITLE
about mapping with rplidar

### ISSUE THREAD

**Issue by CCCCe** [xinjuezou-whi/rplidar_ros2#2]
I have a rplidar in working. So, can I see the result of the mapping with single sensor(rplidar) ? I  didn't find any informations about that.

**Comment by xinjuezou-whi** [comment]
Hello


Do u mean construct a map with rplidar? If so, yes u can see the real mapping result with single sensor, but not from "rplidar_ros2".


u can refer to gmapping, hector_mapping, etc.. for detailed info. Hope this would help
















At 2022-05-26 11:01:34, "CCCCe" ***@***.***> wrote:

I have a rplidar in working. So, can I see the result of the mapping with single sensor(rplidar) ? I didn't find any informations about that.
